// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToaUFcztYfMPHW9fNEZ1Jb1eA2DOt3SM',
    appId: '1:19340169763:web:87c2bc20111366d6ac9796',
    messagingSenderId: '19340169763',
    projectId: 'mobile-1d231',
    authDomain: 'mobile-1d231.firebaseapp.com',
    storageBucket: 'mobile-1d231.firebasestorage.app',
    measurementId: 'G-3S3FWRHE1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChklD0wGIh0Dd3Hs-iiXcmmAnhQsjvm9M',
    appId: '1:19340169763:android:febf1cd01e96a023ac9796',
    messagingSenderId: '19340169763',
    projectId: 'mobile-1d231',
    storageBucket: 'mobile-1d231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcDyZ1Do384QcTeDLpXA050fnW3Etl0Kc',
    appId: '1:19340169763:ios:f444a261cf83b293ac9796',
    messagingSenderId: '19340169763',
    projectId: 'mobile-1d231',
    storageBucket: 'mobile-1d231.firebasestorage.app',
    iosClientId: '19340169763-4nho2tr16qf4p9itihldf9fi3o9qli0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewsAppBilingual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcDyZ1Do384QcTeDLpXA050fnW3Etl0Kc',
    appId: '1:19340169763:ios:f444a261cf83b293ac9796',
    messagingSenderId: '19340169763',
    projectId: 'mobile-1d231',
    storageBucket: 'mobile-1d231.firebasestorage.app',
    iosClientId: '19340169763-4nho2tr16qf4p9itihldf9fi3o9qli0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewsAppBilingual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToaUFcztYfMPHW9fNEZ1Jb1eA2DOt3SM',
    appId: '1:19340169763:web:03f8b4134e0a79ecac9796',
    messagingSenderId: '19340169763',
    projectId: 'mobile-1d231',
    authDomain: 'mobile-1d231.firebaseapp.com',
    storageBucket: 'mobile-1d231.firebasestorage.app',
    measurementId: 'G-JCNTV5JQPE',
  );

}