// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERuj8Mk_mKhqQN_MyiqasrOFiWnMyJ0I',
    appId: '1:539858349367:web:330fd4124536563a287eb2',
    messagingSenderId: '539858349367',
    projectId: 'flutter-firebase-51e66',
    authDomain: 'flutter-firebase-51e66.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-51e66-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-51e66.firebasestorage.app',
    measurementId: 'G-RK4PD4P6EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzWBjI0volRlYwChoSey0cfc-QPy2qt0',
    appId: '1:539858349367:android:f9bdc38609785f42287eb2',
    messagingSenderId: '539858349367',
    projectId: 'flutter-firebase-51e66',
    databaseURL: 'https://flutter-firebase-51e66-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-51e66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzynYTSNIE_BzaVpoh53QYiJfaCu-ZJp0',
    appId: '1:539858349367:ios:cd4e56d3bf0d5e81287eb2',
    messagingSenderId: '539858349367',
    projectId: 'flutter-firebase-51e66',
    databaseURL: 'https://flutter-firebase-51e66-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-51e66.firebasestorage.app',
    iosBundleId: 'com.example.flutterNewsAppBilingual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzynYTSNIE_BzaVpoh53QYiJfaCu-ZJp0',
    appId: '1:539858349367:ios:cd4e56d3bf0d5e81287eb2',
    messagingSenderId: '539858349367',
    projectId: 'flutter-firebase-51e66',
    databaseURL: 'https://flutter-firebase-51e66-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-51e66.firebasestorage.app',
    iosBundleId: 'com.example.flutterNewsAppBilingual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERuj8Mk_mKhqQN_MyiqasrOFiWnMyJ0I',
    appId: '1:539858349367:web:330fd4124536563a287eb2',
    messagingSenderId: '539858349367',
    projectId: 'flutter-firebase-51e66',
    authDomain: 'flutter-firebase-51e66.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-51e66-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-51e66.firebasestorage.app',
    measurementId: 'G-RK4PD4P6EJ',
  );
}
